master: fix failures on partial graph_order
As Christoph stated in #1395 :

	There are issues if graph_order does not cover _all_ fields.

	For graphs that include .negative, rrdgraph fails with a message like

	ERROR: Not a valid vname: crxdrop in line
	GPRINT:crxdrop:LAST:%6.2lf%s/\g

	Where rxdrop is the first field that was not mentioned in graph_order.
	This happens with the if_err_ plugin.

	For graphs without .negative, the order of the remaining fields is
	undefined. I'd expect them to be in the order of appearence as it is if
	there is no graph_order at all.

	The patch below always appends the field names in config order to any
	graph_order given. This results in duplicates in the internal state for
	graph_order but munin_get_field_order will eliminate them before graphing.

Closes: #1395